platform = "windows"

[pyinstaller]
entrypoint = "..\\..\\scripts\\run_local_bot.py"
runtime_name = "bot_core_runtime"
hidden_imports = [
  "bot_core.runtime.bootstrap",
  "bot_core.runtime.pipeline",
  "bot_core.runtime.config",
]
dist_dir = "..\\..\\var\\dist\\pyinstaller\\windows"
work_dir = "..\\..\\var\\build\\pyinstaller\\windows"

[briefcase]
project = "..\\..\\ui\\briefcase"
app = "BotTradingShell"
output_dir = "..\\..\\var\\dist\\briefcase\\windows"

[bundle]
output_dir = "..\\..\\var\\dist\\installers\\windows"
work_dir = "..\\..\\var\\build\\installers\\windows"
qt_dist = "..\\samples\\ui"
include = [
  "config=..\\samples\\config",
  "daemon=..\\samples\\daemon",
  "resources=..\\samples\\resources",
  "reports=..\\samples\\reports",
  "var=..\\samples\\var",
]
wheels_extra = [
  "..\\samples\\wheels\\ccxt-4.0.0-py3-none-any.whl",
  "..\\samples\\wheels\\aiohttp-3.9.5-cp311-cp311-manylinux.whl",
  "..\\samples\\wheels\\lightgbm-4.6.0-cp311-cp311-manylinux.whl",
]
metadata_path = "..\\..\\var\\dist\\installers\\windows\\installer_metadata.json"
